In [61]:
import tensorflow as tf
import pandas as pd
import numpy as np


In [62]:
test = pd.read_csv("/content/sample_data/test_dataset.csv")
train = pd.read_csv("/content/sample_data/train_dataset.csv")

In [63]:
print(train.head)

<bound method NDFrame.head of         CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
460  4.81213   0.0  18.10     0  0.713  ...  666     20.2  255.23  16.42  16.4
461  3.69311   0.0  18.10     0  0.713  ...  666     20.2  391.43  14.65  17.7
462  6.65492   0.0  18.10     0  0.713  ...  666     20.2  396.90  13.99  19.5
463  5.82115   0.0  18.10     0  0.713  ...  666     20.2  393.82  10.29  20.2
464  7.83932   0.0  18.10     0  0.655  ...  666     20.2  396.90  13.22  21.4

[465 rows x 14 column

In [64]:
print(test.head)

<bound method NDFrame.head of         CRIM  ZN  INDUS  CHAS    NOX  ...  RAD  TAX  PTRATIO       B  LSTAT
0    3.16360   0  18.10     0  0.655  ...   24  666     20.2  334.40  14.13
1    3.77498   0  18.10     0  0.655  ...   24  666     20.2   22.01  17.15
2    4.42228   0  18.10     0  0.584  ...   24  666     20.2  331.29  21.32
3   15.57570   0  18.10     0  0.580  ...   24  666     20.2  368.74  18.13
4   13.07510   0  18.10     0  0.580  ...   24  666     20.2  396.90  14.76
5    4.34879   0  18.10     0  0.580  ...   24  666     20.2  396.90  16.29
6    4.03841   0  18.10     0  0.532  ...   24  666     20.2  395.33  12.87
7    3.56868   0  18.10     0  0.580  ...   24  666     20.2  393.37  14.36
8    4.64689   0  18.10     0  0.614  ...   24  666     20.2  374.68  11.66
9    8.05579   0  18.10     0  0.584  ...   24  666     20.2  352.58  18.14
10   6.39312   0  18.10     0  0.584  ...   24  666     20.2  302.76  24.10
11   4.87141   0  18.10     0  0.614  ...   24  666     20

In [78]:
Ind = train[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX','PTRATIO', 'B', 'LSTAT']]
Sub = train[['MEDV']]
print(Ind.head, Sub.head)


<bound method NDFrame.head of         CRIM    ZN  INDUS  CHAS    NOX  ...  RAD  TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31     0  0.538  ...    1  296     15.3  396.90   4.98
1    0.02731   0.0   7.07     0  0.469  ...    2  242     17.8  396.90   9.14
2    0.02729   0.0   7.07     0  0.469  ...    2  242     17.8  392.83   4.03
3    0.03237   0.0   2.18     0  0.458  ...    3  222     18.7  394.63   2.94
4    0.06905   0.0   2.18     0  0.458  ...    3  222     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...  ...      ...     ...    ...
460  4.81213   0.0  18.10     0  0.713  ...   24  666     20.2  255.23  16.42
461  3.69311   0.0  18.10     0  0.713  ...   24  666     20.2  391.43  14.65
462  6.65492   0.0  18.10     0  0.713  ...   24  666     20.2  396.90  13.99
463  5.82115   0.0  18.10     0  0.713  ...   24  666     20.2  393.82  10.29
464  7.83932   0.0  18.10     0  0.655  ...   24  666     20.2  396.90  13.22

[465 rows x 13 columns]> <bound m

In [66]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [67]:
model.fit(Ind, Sub, epochs=1000, verbose=0)
model.fit(Ind, Sub, epochs=10)

Epoch 1/10
15/15 [==============================] - 0s 1ms/step - loss: 27.7763
Epoch 2/10
15/15 [==============================] - 0s 1ms/step - loss: 27.5298
Epoch 3/10
15/15 [==============================] - 0s 1ms/step - loss: 28.2429
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 27.7762
Epoch 5/10
15/15 [==============================] - 0s 1ms/step - loss: 27.8820
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 27.5507
Epoch 7/10
15/15 [==============================] - 0s 1ms/step - loss: 27.8605
Epoch 8/10
15/15 [==============================] - 0s 1ms/step - loss: 27.7485
Epoch 9/10
15/15 [==============================] - 0s 1ms/step - loss: 28.1823
Epoch 10/10
15/15 [==============================] - 0s 1ms/step - loss: 27.4812


In [75]:
print(test_Ind.head)

<bound method NDFrame.head of         CRIM  ZN  INDUS  CHAS    NOX  ...  RAD  TAX  PTRATIO       B  LSTAT
0    3.16360   0  18.10     0  0.655  ...   24  666     20.2  334.40  14.13
1    3.77498   0  18.10     0  0.655  ...   24  666     20.2   22.01  17.15
2    4.42228   0  18.10     0  0.584  ...   24  666     20.2  331.29  21.32
3   15.57570   0  18.10     0  0.580  ...   24  666     20.2  368.74  18.13
4   13.07510   0  18.10     0  0.580  ...   24  666     20.2  396.90  14.76
5    4.34879   0  18.10     0  0.580  ...   24  666     20.2  396.90  16.29
6    4.03841   0  18.10     0  0.532  ...   24  666     20.2  395.33  12.87
7    3.56868   0  18.10     0  0.580  ...   24  666     20.2  393.37  14.36
8    4.64689   0  18.10     0  0.614  ...   24  666     20.2  374.68  11.66
9    8.05579   0  18.10     0  0.584  ...   24  666     20.2  352.58  18.14
10   6.39312   0  18.10     0  0.584  ...   24  666     20.2  302.76  24.10
11   4.87141   0  18.10     0  0.614  ...   24  666     20

In [84]:
print(model.predict(Ind[:5]))
print(model.predict(test[:5]))
print(Sub[:5])

[[29.935055]
 [25.663021]
 [31.108982]
 [30.25207 ]
 [29.622356]]
[[18.442192]
 [13.443125]
 [16.596931]
 [17.036007]
 [18.596468]]
   MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


그럼 각각 봤을때
Ind나 test 값들은 총 13개의 칼럼을 가지고 있었지만 결과적으론 1개의 값들을 출력했고 실제 MEDV랑 비교해보니까 저렇게 차이가 있었다는걸 알수있음
고럼 예측은 이렇게 끝난건가??
그쵸
간단.
어렵네... 이제이걸 그 csv로 뽑아야한다이거지?그렇다고할수있지
그렇다면

In [85]:
pred = model.predict(test)

In [86]:
print(pred)

[[18.442192]
 [13.443125]
 [16.596931]
 [17.036007]
 [18.596468]
 [20.710644]
 [23.216125]
 [22.75931 ]
 [26.219044]
 [16.640526]
 [15.206754]
 [21.31654 ]
 [11.722801]
 [20.154741]
 [23.081419]
 [23.365934]
 [27.53917 ]
 [29.2127  ]
 [20.527859]
 [19.18328 ]
 [22.901218]
 [20.604477]
 [21.471249]
 [14.802283]
 [10.319637]
 [ 5.014805]
 [16.878256]
 [19.254108]
 [21.757317]
 [21.199125]
 [16.84122 ]
 [15.07544 ]
 [20.887339]
 [22.71084 ]
 [19.904142]
 [22.258995]
 [27.359213]
 [26.441723]
 [32.42    ]
 [30.900534]
 [26.813665]]


In [96]:
dataframe = pd.DataFrame(pred, columns=["predictions"])

In [98]:
dataframe.to_csv('/content/sample_data/prediction.csv')